// Generated by CoffeeScript 1.4.0
(function() {
  var col_defs;

  col_defs = [
    {
      sWidth: "30%",
      aTargets: [0]
    }, {
      sWidth: "40%",
      aTargets: [1]
    }
  ];

}).call(this);
